language: python
python:
- "3.6"
- "3.5"
- "2.7"
install: 
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels bioconda
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION bedtools 
  - source activate test-environment
  - python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: isabelleberger
  password:
    secure: OtgXKmnYyMr58czzE/GEz3LnnelQvo2yXyCU7jveyfLFu1kMSi8nKtrUIy9kwj9H4tIg2WWoUQJN0TIkrpJRuRprUnnY/oWXopDr5ndxS+j1OKEqyfPJEeYmPJjnuZlyAVOb42OEGrxylUEC0EUaz23sWe/Ui9RWBJ2vQg5Klp1bZ+XFxHl5LohDrWQezFvwwTKkLvQ9WrmNfsQL0jsjKfUgDq0iltpsy+tp5Z7y+BzGIuYdotWnfADWhF6/UGkISO1Oczb23tMMKQ1Pm99MDYy8HQ5dQX19O0VXJVsnJKir0v/S4Xd+q7DZwzhZ1YsYWRrrHaosMrK3MIPndYwhXxZClfA/lRKyHMRE7spmebpeX4P/XM3ujKvI3dz75M322n7AWDxYp82TwesW8YA9B05mjh1881zaK6wlrg8Lz8pQc9eVJqcyl1KdKb/ptVmHJnaGS5UctAM01iVaYMvIxkgKXxhmrIFuA9FgCTkN2krfvZiGODOCDIhxVGkHNMPEmnHo8Wb3b3pL7c4SIm3FQFouet0KapHOL3RUXhYrDfOqdKqmY4deH7sclb+7I9eUKJSPkXevanykJYrDxIhKjW5b6Gs13R8FjHZPP0son42V5aje+c3Yw3CZqhtrzUFkr/X+9+Wce+6yASAgYZrK9KA2ozJrvUrPLbTgiqNatGc=
  on:
    tags: true
    repo: isabelleberger/targeneintersect
    python: 3.6
